### ISSUE TITLE
using pythonnet-docker to run interop com of office

### ISSUE THREAD

**Issue by jjab2020** [pythonnet/pythonnet-docker#4]
hello,
first thank you very much for this docker,

Can i use it to make a c# programm using library interop, because i want to convert file ppt to wmv video.

Thank you very much.

**Comment by den-run-ai** [comment]
Hi,

This is not possible. Out of scope of this container.

**Comment by vmuriart** [comment]
You can use one of these docker files to work w `pywin32`.

https://github.com/scottbelden/docker-winpyinstaller/tree/master/build
https://github.com/mazaclub/tate/blob/master/contrib/tate-release/Dockerfile

In your case, it sounds like you would be trying to load Office into docker which isn't a native program for it. In theory it could be done, but its outside the scope of this pr. The link below has a discussion on loading office into docker.

https://www.quora.com/Can-I-put-Microsoft-Office-2013-in-a-Docker-container-and-then-ship-it-to-Ubuntu-14-04

**Comment by jjab2020** [comment]
Oh thank you very much for your useful help I have build a wine container with python and pywin , at this moment I want to install office , can I use pywin with interop runtime only without installing office in my wine docker.
